### ISSUE TITLE
inncecesary request

### ISSUE THREAD

**Issue by LucasAlgerDay** [delefault/Amino-kick-chat-users#1]
![image](https://github.com/delefault/Amino-kick-chat-users/assets/88118098/941276e9-49d4-4d15-afe3-5ba06dad8b34)
the blue part is innecesary, the function where you get the users in the chat return too his level, is innecesary get user_info

**Comment by Delafault** [comment]
Why?.. You have to check the level of users.

**Comment by LucasAlgerDay** [comment]
Because the function get_chat_users return his level of the profile so, with the get_user_info you will get the level again.

just do something like `for user, level in zip(chat_users.userId, chat_users.level):` because chat_users had too the level.

**Comment by Delafault** [comment]
Thanks.
